### ISSUE TITLE
Genesis Map

### ISSUE THREAD

**Issue by JackJack33** [Minehut/TeamGG-Rotations#1]
By me, and myself, and I. No one else <3
[http://www.mediafire.com/file/0ud7p3nkpp7r9cx/GenesisMap.schematic](url)
![2017-05-07_14 26 28](https://user-images.githubusercontent.com/30203676/28243030-dacb28de-6982-11e7-89af-038b2feb637c.png)
![2017-05-07_14 25 44](https://user-images.githubusercontent.com/30203676/28243031-dada9404-6982-11e7-96dc-8d47b31edf5b.png)
![2017-05-07_14 26 04](https://user-images.githubusercontent.com/30203676/28243032-dae38db6-6982-11e7-887f-0441b935d9eb.png)
![2017-05-07_14 26 17](https://user-images.githubusercontent.com/30203676/28243033-dae3ce70-6982-11e7-8be9-dda836e2fc06.png)

**Comment by tjhubz** [comment]
Issues:
Should be in TeamGG-Maps repo,
Map is in schematic form, need .zip
Needs map.json
