### ISSUE TITLE
Exile Map

### ISSUE THREAD

**Issue by JackJack33** [Minehut/TeamGG-Rotations#2]
A map by me, Glayzed, and Spiderlogical (and suggestions from Mini_Meatwad!).

[Schematic Link](https://www.mediafire.com/?v4u5wy93ba4smki)

![2017-07-15_23 06 48](https://user-images.githubusercontent.com/30203676/28244584-d4187592-69b3-11e7-8613-6187ce48d9f2.png)
![2017-07-15_23 06 36](https://user-images.githubusercontent.com/30203676/28244586-d421269c-69b3-11e7-965f-2b9cde87b272.png)
![2017-07-15_23 06 29](https://user-images.githubusercontent.com/30203676/28244588-d42145b4-69b3-11e7-9c40-0766aa077c3e.png)
![2017-07-15_23 06 23](https://user-images.githubusercontent.com/30203676/28244587-d42135c4-69b3-11e7-98bf-cc6a29048947.png)
![2017-07-15_23 06 12](https://user-images.githubusercontent.com/30203676/28244585-d4208570-69b3-11e7-9240-05e9b0d305c0.png)
![2017-07-15_23 06 05](https://user-images.githubusercontent.com/30203676/28244589-d42288a2-69b3-11e7-8822-4ab3726a0f53.png)
![2017-07-15_23 05 55](https://user-images.githubusercontent.com/30203676/28244590-d426129c-69b3-11e7-8ed4-e6e575787274.png)
![2017-07-15_23 17 20](https://user-images.githubusercontent.com/30203676/28244591-d42dc564-69b3-11e7-9906-09eacdd1df1d.png)

**Comment by xSpiderMC** [comment]
It's awesome!!

**Comment by tjhubz** [comment]
Issues:
Should be in TeamGG-Maps repo,
Map is in schematic form, need .zip
Needs map.json

**Comment by tjhubz** [comment]
Look at a map in the TeamGG-Maps repo for an example of a map.json
